name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - name: Lint XtendM3 Extensions
        run: mvn -B xtendm3:lint --file pom.xml
      - name: Export XtendM3 Extensions
        run: mvn -B xtendm3:export --file pom.xml
      - uses: actions/upload-artifact@v2
        name: Upload exported extensions
        if: ${{ success() }}
        with:
          name: exported-extension
          path: target/exported.zip
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
